[package]
name = "ledgeracio"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPLv3+"

[dependencies]
# substrate-subxt = { git = "ssh://github.com/paritytech/substrate-subxt", branch = "staking" }
substrate-subxt = { path = "../substrate-subxt" }
structopt = "0.3.14"
codec = { package = "parity-scale-codec", version = "1.3.0" }
sp-core = { version = "2.0.0-rc2", features = ["full_crypto", "std"] }
frame-support = "2.0.0-rc2"
async-std = { version = "1.5.0", features = ["attributes"] }
ed25519-bip32 = "0.3.1"
futures = "0.3.5"
hmac = "0.7.1"
sha2 = "0.8.2"
tiny-bip39 = "0.7.3"
hex = "0.4.2"

[profile.release]
lto = "fat"
codegen-units = 1
incremental = false
