[package]
name = "ledgeracio"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPLv3+"

[dependencies]
substrate-subxt = { git = "ssh://github.com/paritytech/substrate-subxt", branch = "staking" }
structopt = "0.3.14"
sp-core = "2.0.0-alpha.7"
codec = { package = "parity-scale-codec", version = "1.3.0" }
sp-runtime = "2.0.0-alpha.7"
frame-support = "2.0.0-alpha.7"
async-std = { version = "1.5.0", features = ["attributes"] }
