[package]
name = "ledgeracio"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPLv3+"

[dependencies]
# substrate-subxt = { git = "ssh://github.com/paritytech/substrate-subxt", branch = "staking" }
substrate-subxt = { path = "../substrate-subxt" }
structopt = "0.3.14"
codec = { package = "parity-scale-codec", version = "1.3.0" }
frame-support = "2.0.0-rc3"
async-std = { version = "1.5.0", features = ["attributes", "unstable"] }
ed25519-bip32 = "0.3.1"
futures = "0.3.5"
hmac = "0.8.0"
sha2 = "0.9.0"
tiny-bip39 = "0.7.3"
hex = "0.4.2"
thiserror = "1.0.19"

ledger-kusama = { git = "https://github.com/Zondax/ledger-kusama-rs" }
zx-bip44 = { git = "https://github.com/Zondax/blockchain-tools-rs" }
ledger-zondax-generic = { git = "https://github.com/Zondax/ledger-rs", branch="feature/upgradehid" }
ledger-transport = { git = "https://github.com/Zondax/ledger-rs", branch="feature/upgradehid" }
ledger-transport-hid = { git = "https://github.com/Zondax/ledger-rs", branch="feature/upgradehid" }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
incremental = false
opt-level = 3
