[licenses]
unlicensed = "deny"
copyleft = "allow"
allow-osi-fsf-free = "either"

[[licenses.clarify]]
name = "ring"
expression = "OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
deny = [
    { name = "parity-util-mem", version = "<0.6" }
]

[sources]
allow-git = [
    "https://github.com/DemiMarie/substrate-subxt.git",
    "https://github.com/Zondax/ledger-substrate-rs.git",
    "https://github.com/Zondax/ledger-rs.git",
    "https://github.com/Zondax/blockchain-tools-rs.git",
    "https://github.com/paritytech/substrate.git",
    "https://github.com/paritytech/substrate-subxt.git",
]
