name: Cargo clippy

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - 'README.md'

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install development packages necessary for the build
        run: sudo apt-get install libudev-dev protobuf-compiler
      - name: Install clippy
        run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings -D clippy::pedantic -D clippy::correctness -D clippy::complexity -D clippy::perf
